version: "3.5"

services:
  db:
    container_name: 'hambabwa_mysql'
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - hambabwa-net
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - hambabwa-net
  hambabwa:
    container_name: 'hambabwa_backend'
    build:
      context: .
    restart: always
    links:
      - db
    depends_on:
      - db
      - redis
    ports:
      - "${PORT}:${PORT}"
    networks:
      - hambabwa-net
    env_file:
      - ./config/.env.${NODE_ENV}
networks:
  hambabwa-net:

